hpsint/hpsint

applications/sintering/include/pf-applications/sintering/driver.h, applications/sintering/include/pf-applications/sintering/postprocessors.h
This is in order to make images like this:
The most coarse mesh has to adjusted to fit the bounding box boundaries if one wants to have a perfect flat cut plane without "steps".
This PR has to be rebased after #489 is merged
=> Use filter bounding box for surface and grain boundary contours

applications/sintering/include/pf-applications/sintering/driver.h, applications/sintering/include/pf-applications/sintering/parameters.h, applications/sintering/include/pf-applications/sintering/postprocessors.h
Similar to grains contourse but for variable `c`.
Has to be rebased once #491 is merged.
NB: a smarter function can then be written to remove some code duplication.
=> Concentration contours

applications/sintering/include/pf-applications/sintering/initial_values_cloud.h, applications/sintering/include/pf-applications/sintering/parameters.h, applications/sintering/sintering.cc
Recently I tried to run cases with zero thickness interface. They worked, but the obtained initial colorization is far suboptimal.
=> Radius buffer for clouds initial coloring

applications/sintering/include/pf-applications/sintering/parameters.h, applications/sintering/sintering.cc
One can do now something like this and redefine certain options directly from the command line:
```
./applications/sintering/sintering-2D-generic-scalar --circle 7.5 2 settings.json --TimeIntegration.TimeStepInit=1e-1
```
=> Override certain parameters via command line

applications/sintering/include/pf-applications/sintering/operator_sintering_coupled_base.h
There was a bug in the MPI case.
=> Fix indexing

applications/sintering/analysis_examples/2d_titanium.json, applications/sintering/analysis_examples/2particles_pbc.json, applications/sintering/analysis_examples/3d_default.json, applications/sintering/analysis_examples/49particles.json, applications/sintering/analysis_examples/49particles_delta_min_05.json, applications/sintering/analysis_examples/49particles_delta_min_10.json, applications/sintering/analysis_examples/49particles_delta_min_20.json, applications/sintering/analysis_examples/49particles_delta_min_30.json, applications/sintering/analysis_examples/49particles_delta_min_40.json, applications/sintering/analysis_examples/49particles_delta_min_40_coarse.json, applications/sintering/analysis_examples/49particles_delta_min_40_ultimate.json, applications/sintering/analysis_examples/49particles_delta_min_40_wang.json, applications/sintering/analysis_examples/49particles_delta_min_50.json, applications/sintering/analysis_examples/49particles_delta_min_50_coarse.json, applications/sintering/analysis_examples/49particles_iso.json, applications/sintering/analysis_examples/5particles.json, applications/sintering/analysis_examples/default.json, applications/sintering/analysis_examples/termuhlen.json, applications/sintering/include/pf-applications/sintering/driver.h, applications/sintering/include/pf-applications/sintering/parameters.h, include/pf-applications/grain_tracker/distributed_stitching.h, include/pf-applications/grain_tracker/grain.h, include/pf-applications/grain_tracker/segment.h, include/pf-applications/grain_tracker/tracker.h, tests/distributed_stitching_02.cc, tests/grain_tracker_advection_periodic.cc, tests/grain_tracker_periodic_corner.cc, tests/include/tangent_tester.h
It seems that for coarse meshes a given order parameter can have values a bit higher than the threshold values in the vicinity of grains. Such situations for coarse meshes are not easy to control so I decided to introduce a tighter threshold for new grains. It make sense since sometimes it is not easy to distinguish a new grain appearing from numerical noise. At least the last case from [this comment](https://github.com/hpsint/hpsint/pull/520#issuecomment-1498701896) seems to work.
=> More reliable filtering of new grains for the grain tracker

include/pf-applications/lac/dynamic_block_vector.h
When working on #524, I also thougth that the issue might have come from DBV. I found another inconsistency there. If new blocks are added here via reinit, they turn out to be always without ghost values. This is not a desirable behavior I guess since all blocks of DBV should be of the same state regarding ghosts. And then I observed something like this by checking this situation immediately after https://github.com/hpsint/hpsint/blob/494d433774f7e3f952deb2a7537f62aab935813c/applications/sintering/include/pf-applications/sintering/driver.h#L1784-L1785
```
Running: ./applications/sintering/sintering-2D-generic-scalar ./applications/sintering/sintering-2D-generic-scalar --cloud /home/kapusta/development/hpsint/applications/sintering/sintering_cloud_examples/5particles.cloud …
```
=> Update ghosts in dynamic block vector

CMakeLists.txt, applications/sintering/include/pf-applications/sintering/operator_sintering_generic.h, benchmarks/CMakeLists.txt, benchmarks/README.MD, benchmarks/fe_values_vs_fe_eval.cc, benchmarks/layer_wise.likwid.cc, benchmarks/layer_wise_00.json, benchmarks/layer_wise_01.json, benchmarks/layer_wise_02.json, benchmarks/layer_wise_03.json, benchmarks/operators.h
Helmholtz-Operator with `FEValues` (first two columns) and `FEEvaluation` (third column) on a Cartesian mesh (40 procs):
```
| dim | fe_type | n_dofs  | n_components | t_0        | t_1        | t_2        | 
| 3   | FE_Q    | 2146689 | 1            | 5.8874e-02 | 1.2177e-01 | 3.4334e-03 | 
| 3   | FE_Q    | 4293378 | 2            | 1.2809e-01 | 2.4782e-01 | 6.1621e-03 | 
| 3   | FE_Q    | 6440067 | 3            | 1.9842e-01 | 3.6287e-01 | 1.0750e-02 | 
| 3   | FE_Q    | 8586756 | 4            | 3.0696e-01 | 4.4631e-01 | 1.2051e-02 |
```
One can see speedups of factor 17-25. For 2D the values are somewhat lower but not much.
=> Add benchmark with FEValues

applications/sintering/include/pf-applications/sintering/instantiation.h, applications/sintering/include/pf-applications/sintering/operator_base.h, applications/sintering/include/pf-applications/sintering/operator_sintering_generic.h
A more flexible macro that is well in sync now with `MAX_SINTERING_GRAINS`.
=> Improve code generation for different number of grains using boost preprocessor

applications/sintering/include/pf-applications/sintering/postprocessors.h
The very first cells was missing, the output was like this (see bottom left corner):
Now fixed.
=> Fix missing first cell

applications/sintering/include/pf-applications/sintering/driver.h, applications/sintering/include/pf-applications/sintering/parameters.h, applications/sintering/include/pf-applications/sintering/postprocessors.h
For convenience, if a pore touches the boundary, it is eliminated from the output. I need to check what output this approach will generate, whether it will look representative for large packings.
=> Output pores contours

applications/sintering/include/pf-applications/sintering/operator_sintering_coupled_base.h, applications/sintering/include/pf-applications/sintering/preconditioners.h, applications/structural/include/pf-applications/structural/operator_elastic_linear.h
Our indices are local, but `clear_row()` operates. As the result, the mechanical boundary conditions in MPI case were imposed wrongly for ranks >= 2, like this:
whereas it should be like this:
=> Fix indices in `clear_row()` call

benchmarks/operators.h
Intel compiler fails to compile the likwid benchmark complaining about the `internal` namescpase ambiguity.
=> Add dealii namespace

include/pf-applications/grain_tracker/distributed_stitching.h, include/pf-applications/grain_tracker/tracker.h
Local indices had to be deoffsetted buy `local_offset` when accessing entries in `local_particle_max_values`.
=> Fix bug in obtaining max values per segment inside GrainTracker

tests/grain_tracker_advection_periodic.mpirun=4.output, tests/grain_tracker_periodic_corner.mpirun=4.output
Some grain tracker tests got broken after #553. This PR fixes them.
=> Add max value to the output

applications/sintering/include/pf-applications/sintering/operator_advection.h, include/pf-applications/grain_tracker/tracker.h
The nearly desappearing grains had to be properly marked as invalid in the `particle_ids_to_grain_ids` mapping. A tricky bug that used to trigger crash very rarely.
=> Mark invalid grains in the grain tracker

include/pf-applications/grain_tracker/output.h, include/pf-applications/grain_tracker/tracker.h, include/pf-applications/grain_tracker/tracking.h
Should be rebased and merged after #565.
But can be already reviewed.
=> Extract print functions for the grain tracker

include/pf-applications/grain_tracker/tracking.h, tests/transfer_grain_ids_07.cc, tests/transfer_grain_ids_07.output, tests/transfer_grain_ids_08.cc, tests/transfer_grain_ids_08.output, tests/transfer_grain_ids_09.cc, tests/transfer_grain_ids_09.output
Basically, the main modification is that a set of `rtree` boxes is created not from the new grains, but from the old ones. This makes more sense since in our application it is assumed that the old grains may disappear but not any new ones are allowed to appear. 
Previously, I have observed the following error. Assume at $t=t_0$ we have 2 old grains: $G_1^0$ and $G_2^0$. At the next step $G_2$ disappears, $G_1$ remains and moves slightly such that its bounding box overlaps both the boxes of $G_1^0$ and $G_2^0$. The previous algo would at first map $G_1^0 \rightarrow G_1$ (which is something we need) and then happily override it with $G_2^0 \rightarrow G_1$. This is due to the fact that the set of new grains is smaller and `rtree` is simply not aware of a better candidate at each particular …
=> Improve the rtree based grain tracking algo

applications/sintering/include/pf-applications/sintering/driver.h
=> Skip reassignment for the second `track()` in the case of advection

applications/sintering/include/pf-applications/sintering/operator_sintering_generic.h, applications/sintering/include/pf-applications/sintering/preconditioners.h, tests/residual_generic_scalar_rbm.mpirun=1.output, tests/residual_generic_scalar_rbm.mpirun=2.output, tests/residual_generic_scalar_rbm.mpirun=3.output, tests/residual_generic_tensorial_rbm.mpirun=1.output, tests/residual_generic_tensorial_rbm.mpirun=2.output, tests/residual_generic_tensorial_rbm.mpirun=3.output
The advection term is slightly rewritten and it turned out that the new form keeps mass conservation whereas the previous one violated it. So, our advection term (will show it only for $c$) looks like this:
$-\nabla \cdot (c\mathbf{v}) = -\nabla c\cdot \mathbf{v} - c \nabla \cdot \mathbf{v}$
I have omitted the second term here since our velocities are constant within each grain (and seems to be an incorrent assumption that lead to the erroneous behavior). Keeping this assumption in mind, the weak form for the advection term was written as
$-\left(\nabla c\cdot \mathbf{v}, \phi_c \right)$
When studying the mass conservation I observed that it get violated. However, with this version of the advection term in the weak form, the mass conservation of the CH equation is preserved:
$\left(c …
=> Advection with conservation

applications/sintering/include/pf-applications/sintering/operator_advection.h, applications/sintering/include/pf-applications/sintering/parameters.h, tests/include/sintering_model.h
It was a bit confusing that previously parameter `cgb` did not influence on anythig since the normalization was disabled in the code. I decided to bring it back in order to perform easier comparison with other researchers (because many people use it), but it still can be disabled (and that is the default behavior) if `cgb < 0`.
=> Customize normalization in OperatorAdvection

applications/sintering/scripts/centrify_packing.py
A handy script to centrify packing to the origin of coordinates. The need for that emerged in order to apply the same control box for nested packings. It is more conveninent to have the packings then centered at 0.
=> Add script to centrify packings

applications/sintering/batch_runs/jobs_submitter.py
A script that submits a list of jobs limitting the slurm queue manually. This is useful, for instance, for submitting 3+ jobs to a test partition of SuperMUC. The script takes the complete list of jobs to be submitted and then checks in an infinite loop that only 2 are submitted at the same time.
=> Script that schedules sbatch jobs

applications/sintering/include/pf-applications/sintering/driver.h, applications/sintering/include/pf-applications/sintering/parameters.h, applications/sintering/include/pf-applications/sintering/postprocessors.h
Sometimes for lower shrinkage rates 10 subidvisions is too low to have nice curves.
=> Shrinkage custom intervals

applications/sintering/include/pf-applications/sintering/driver.h, applications/sintering/include/pf-applications/sintering/parameters.h, applications/sintering/include/pf-applications/sintering/postprocessors.h
When the bounding box filter is used, then porosity contours generated from the quantity (1-c) look better than those based on the pore ids. I decided to keep two options available and one can choose the desirable output manually.
=> Smooth porosity contours

applications/sintering/include/pf-applications/sintering/postprocessors.h
With the recent deal.II builds this exception started to be triggered in debug https://github.com/dealii/dealii/blob/7fd45dbe84557fd597724d8758e47d1a33c1653f/source/fe/mapping_fe.cc#L2279-L2282 inside `output_grain_contours_vtu()`. This is beacuse another branch of the "if" condition started to work here https://github.com/dealii/dealii/blob/7fd45dbe84557fd597724d8758e47d1a33c1653f/source/fe/fe_values.cc#L333, I guess that the default `update_flags` got changed somewhere (since we do not set the up in the contours output) and the influenced the default behavior of `DataOut`.
=> Reset all manifolds

applications/sintering/analysis_examples/termuhlen.json, applications/sintering/include/pf-applications/sintering/driver.h, applications/sintering/include/pf-applications/sintering/parameters.h, include/pf-applications/grid/bounding_box_filter.h
Sometimes I need to compute various quantities in various volumes of interest (control boxes) within the same simulation. The output is adjusted such that for the same run one can have multiple control boxes and also output quantities for the whole domain. Previously it was either the whole domain or the given control box.
```json
{
"OnlyControlBoxes": "false",
"ControlBoxes": "2,2,-4 ; 27.5,32,4 | 4,5,4 ; 25,27,4"
}
```
The option `OnlyControlBoxes=false` disables the output only for the control boxes, meaning that the quantities and/or contours will be built also for the entire domain. By default is set to `false`.
The option `ControlBoxes` in the case above defines 2 volumes of interest with the `bottom_left x top_right` points as follows:
1. (2, 2, -4) x (27.5, 32, 4)
2. (4, 5, 4) x …
=> Multiple control boxes

applications/sintering/include/pf-applications/sintering/driver.h, applications/sintering/include/pf-applications/sintering/parameters.h, include/pf-applications/grain_tracker/tracker.h, include/pf-applications/grain_tracker/tracking.h, tests/transfer_grain_ids_12.cc, tests/transfer_grain_ids_12.output, tests/transfer_grain_ids_13.cc, tests/transfer_grain_ids_13.output
Add some vorbisity levels in order to reduce the output details in certain cases.
Also some exceptions made more readable.
It would be better to use `LogStream`, but that is better to be properly implemented application-wise. So I took a simpler approach that does the job at the moment.
=> Customize grain tracker logging

applications/sintering/include/pf-applications/sintering/postprocessors.h
In relation to #234.
It turned out that `center()` provides more accurate results than `barycenter()`. These inaccuracies led to wrong estimates of shrinkage.
With `barycenter()`:
With `center()`:
I also made tolerance to be relevant to the cell size.
=> Use center instead of barycenter

applications/sintering/include/pf-applications/sintering/driver.h, include/pf-applications/grain_tracker/tracker.h
Also fix counter initialization if `old_grains` map is empty.
=> Call grain tracker initialization if `track_with_quality = true`

applications/sintering/include/pf-applications/sintering/driver.h, applications/sintering/include/pf-applications/sintering/operator_advection.h
The call was missing in one of the situations. Exception message was also improved.
=> Courant fix `precompute_cell_diameters()` calls

applications/sintering/include/pf-applications/sintering/advection.h
The indices for torque were wrong. It was difficult to notice that previously since I normally do not use rotational contributions.
I also split velocities into two components for convenience.
`has_velocity()` returns false if the velocity data is completely empty.
=> GT velocity: fix indices for torque, split velocities and modify `has_velocity()` condition

applications/sintering/include/pf-applications/sintering/advection.h, applications/sintering/include/pf-applications/sintering/driver.h, applications/sintering/include/pf-applications/sintering/operator_sintering_generic.h, applications/sintering/include/pf-applications/sintering/parameters.h, applications/sintering/include/pf-applications/sintering/postprocessors.h
Two ways of the output: from the operator (builds a continuous velocity field) and cell-wise, based on the data contained inside grain tracker.
=> Output advection velocities

applications/sintering/include/pf-applications/sintering/driver.h, applications/sintering/include/pf-applications/sintering/operator_advection.h, applications/sintering/include/pf-applications/sintering/parameters.h, tests/include/sintering_model.h
I observed that the initial discontinuous definition of the grain boundary filter 
oftern leads to issues with the nonlinear solver. So I decided to introduce a smoothened function like this:
The functions look like this ($s_{gb}=0.14$):
The influence on the accuracy for a simple 2 particles test:
For a more comples test of 8 particles in a chain one can see the benefit of the new continuous definition. The default one start exhibiting numerical problems at around $t=75$ and then collapses at $t=120$.
=> Smooth grain boundary filter for the Wang sintering forces

applications/sintering/include/pf-applications/sintering/operator_advection.h, applications/sintering/include/pf-applications/sintering/parameters.h, tests/include/sintering_model.h
The value `-1` has been always confusing me. In fact, `cgb = 0` already means that there is no normalization should be applied.
=> Use cgb = 0 to disable normalization (less confusing)

applications/sintering/scripts/paraview_2particles.py, applications/sintering/scripts/plot_data.py
This script extracts neck growth and shrinkage from the VTK data. Though it can be applied to any particles assemblies, the measurement of the neck size is tuned for the case of a 2 particles system.
The idea appeared when I tried to analyze if the compressive Wang forces in combination with the diffusion properties deliver the same kinematics for systems of different scale. To this end, I run the 2 particles case in 2D with different particles radii: 10 and 20. Of course, the system with larger particles will sinter much longer, but the idea was to check if the sitenring forces, the neck growth and the shrinkage rate are qualitatively comparable: the curves should align if the time is normalized. As one can see, this is indeed the case. For the smaller particles case I used …
=> Obtain necks from the VTK files for the 2 particles systems

applications/sintering/include/pf-applications/sintering/driver.h
I usually try to keep `max_refinement_depth` as low as possible in order to lower the number of dofs. However, sometimes it turns out to be too low and then `quality_min` can not be achieved. As the result, if the mesh quality monitoring is enabled, the solver attempts to refine mesh at every thimestep without any visible result. This PR detects such situation after the first timestep and increases `max_refinement_depth` accordingly to comply with `quality_min`.
=> Adjust refinement strategy if mesh quality can not be reached

applications/sintering/scripts/postproc_shrinkage.py
This together with #639 allows one to output compressive strain averaged over different locations (i.e. particles) of the packing to check if the overall densification was homogeneous or not.
=> Custom reference particles for shrinkage

applications/sintering/include/pf-applications/sintering/operator_sintering_coupled_base.h, applications/sintering/include/pf-applications/sintering/parameters.h, applications/structural/include/pf-applications/structural/tools.h
Output linearized strain for the current timestep, it is quite naive and can be used mainly for control plausibility of the results.
=> Output naive linear strain

applications/sintering/scripts/build_tex_packings.py, applications/sintering/scripts/library.py
This is the generalization of @peterrum's script used for making some nice images in the solver paper. This version allows to create images like this:
```
python build_tex_packings.py -f contour_solution.1.txt contour_solution.23.txt contour_solution.236.txt \ 
-o plot.tex --scale=5 --show-topology --label-order-params --coarsening=5
```
or
```
python build_tex_packings.py -f contour_solution.1.txt contour_solution.23.txt contour_solution.236.txt \
-o plot.tex --scale=5 --show-simplified
```
or
```
python build_tex_packings.py -f contour_solution.1.txt contour_solution.23.txt contour_solution.236.txt \ 
-o plot.tex --scale=5 --show-topology --show-simplified --label-order-params --coarsening=5 --circle-opacity=0.4
```
[contour_solution.1.txt](https://github.com/hpsint/hpsint/files/15096948 …
=> Build tex clouds

applications/sintering/include/pf-applications/sintering/driver.h, applications/sintering/include/pf-applications/sintering/parameters.h
I noticed that performance-wise it is better to use the mesh quality from the first timestep rather than set it up manually, in order to keep the number of degrees of freedom under control. This PR implements this strategy.
=> Auto min mesh quality

applications/sintering/include/pf-applications/sintering/driver.h
Previously parameters `current_min_mesh_quality` and `current_max_refinement_depth` were overwritten with the default values when restart is performed.
=> Fix `current_min_mesh_quality` and `current_max_refinement_depth` on restart

applications/sintering/include/pf-applications/sintering/driver.h, applications/sintering/include/pf-applications/sintering/operator_sintering_data.h, applications/sintering/include/pf-applications/sintering/operator_sintering_generic.h, applications/sintering/include/pf-applications/sintering/preconditioners.h
Previous implementation was a bit intrusive. The way how advection terms should be evaluated in preconditioners are , in general, dictated by the nonlinear operator, so it makes sense to delegate this step to `NonLinearOperator` which is now provided via the template parameter. The branches which were responsible for evaluations for the case of the coupeld Wang operator will be similarly integrated later to the coupled operator itself.
=> Precondition advection terms via nonlinear operator

applications/sintering/include/pf-applications/sintering/driver.h
Grain tracker has to be enabled for `CentralParticle` and `CentralParticleSection` boundary conditions. Also we need to check if the grains are stored in the GT when computing the average coodrination number.
=> Improve checks whether GT is enabled

.github/workflows/indentation.yml
I guess this should fix the indentation workflow.
=> Update clang-format-lint-action version

include/pf-applications/grain_tracker/distributed_stitching.h, tests/distributed_distances.cc, tests/distributed_distances.mpirun=4.output
This is another way to estimate distance between particles cloud. It is a kind of iterative weighted flooding algorithm where at each iteration a single layer of cells is colored. The detailed explanation are in the comments across the code.
Some images for better understanding. This is the initial configuration used, there is AMR for greater complexity. `particles_ids` are the indices from the distributed stitching algo.
This is a tricky area where a few cells of a grain are on the neighboring ranks:
This is how `particle_distances` look at the very beginning of the process - only the outer layer of grains is picked and its distance is set to 0:
These are the corresponding `particle_markers` - they are simply global indices of the grains:
This is the final output of `particle_distances`: …
=> Distributed distances between particles

applications/sintering/include/pf-applications/sintering/postprocessors.h, include/pf-applications/grain_tracker/distributed_stitching.h, include/pf-applications/grain_tracker/ellipsoid.h, include/pf-applications/grain_tracker/tracker.h, tests/grain_tracker_elliptical.mpirun=4.output
The ellipsoid radii are evaluated from the 3 principal inertia moments. This is a reasonable approximation that though contains a drawback: for certain geometries the radii may get smaller than the actual grain thus not the whole grain is covered by the ellipsoid. To avoid this, the PR introduces the following scaling algo:
1) identify the outmost point of each grain,
2) if this point is outside of the bounding ellipsoid, then the intersection with the ellipsoid is identified using the previously developed function `find_new_t()` which has been renamed to `find_ellipsoid_intersection()`,
3) the obtained value of `t` is then used to scale the ellipsoid radii preserving thus their aspect ratio.
=> Scale ellipsoids

applications/sintering/include/pf-applications/sintering/driver.h, applications/sintering/include/pf-applications/sintering/parameters.h, include/pf-applications/grain_tracker/output.h, include/pf-applications/grain_tracker/tracker.h
A bit of refactoring of two output functions which are mainly used for debugging of the grain tracker behavior.
=> Refactor particles output: particles indices and as spheres

include/pf-applications/grain_tracker/ellipsoid.h, include/pf-applications/grain_tracker/elliptical_helpers.h, include/pf-applications/grain_tracker/representation.h, include/pf-applications/grain_tracker/tracker.h, tests/complex_microstructure.cc, tests/complex_microstructure.mpirun=4.output, tests/grain_tracker_elliptical.mpirun=4.output
The scaling introduced previously in #687 had a minor error in evaluataion of the scaling factor, but what is more important, it was not sufficient for some cases. Even if the most remote point got covered by the ellisoid in the first check, there are still can be points (e.g. located along the axis of the smallest radius) that fall outside on the ellipsoid. The first check minimizes the number of points to be checked at this step.
Here is the small demonstation how these scalings work (for the grains assigned to the order parameter `op=0`) on the basis of the microstructure test added in #689.
**no scaling**:
**scaling via the most remote points**:
**additional scaling**:
The grains drawing is not perfect since the corresponding python script needs improvement, that will be done in the …
=> Improve ellipsoids scaling

applications/sintering/include/pf-applications/sintering/postprocessors.h, applications/sintering/scripts/build_tex_packings.py, applications/sintering/scripts/library.py, include/pf-applications/grain_tracker/representation.h, include/pf-applications/grain_tracker/segment.h, tests/complex_microstructure.cc
This PR adds to features to the tex contours builder:
1. Elliptical grain representations
2. Grains can be nonconvex, `alphashape` from python is used for that. Since the contours building can take a while, this process is done in parallel.
As the result, such nice pictures can be obtained for the microstructure from #689 and #692:
`op=0`:
`op=1`:
=> Build elliptical representation and nonconvex grains

applications/sintering/include/pf-applications/sintering/free_energy.h, include/pf-applications/numerics/power_helper.h, tests/power_sum.cc, tests/power_sum.output
For the proper implementation of the grain growth model, we need to refactor a bit the existing code to make it not so much dependent on the energy functional and on the number of unknown fields (i.e., sometimes we do not have CH or AC components at all). This is a first PR in a sequence to implement this.
=> Extract PowerHelper and add a test for it

applications/sintering/include/pf-applications/sintering/driver.h, applications/sintering/include/pf-applications/sintering/operator_base.h, applications/sintering/include/pf-applications/sintering/parameters.h, applications/sintering/include/pf-applications/sintering/preconditioners.h, applications/sintering/sintering_throughput.cc, include/pf-applications/lac/evaluation.h, include/pf-applications/lac/preconditioners.h, tests/include/pf-applications/tests/tangent_tester.h
When implementing a new operator, it would be nice to have an option just to code the RHS first and then immediately try to solve a demo problem using the jacobi free approach. For simplicity, one can use ILU, for instance, but in requires a tangent matrix still. So I added an option to provide such a matrix using finite differences.
=> FDM approximation of the system matrix for preconditioners

applications/sintering/include/pf-applications/sintering/initial_values_array.h, applications/sintering/include/pf-applications/sintering/initial_values_ch_ac.h, applications/sintering/include/pf-applications/sintering/initial_values_circle.h, applications/sintering/include/pf-applications/sintering/initial_values_cloud.h, applications/sintering/include/pf-applications/sintering/initial_values_hypercube.h, applications/sintering/include/pf-applications/sintering/initial_values_microstructure.h, applications/sintering/include/pf-applications/sintering/initial_values_microstructure_imaging.h, applications/sintering/include/pf-applications/sintering/initial_values_microstructure_voronoi.h, applications/sintering/include/pf-applications/sintering/initial_values_spherical.h, applications/sintering/include/pf-applications/sintering/runner.h
This is required for grand potential phase-field models.
=> Add option to treat first variable of the CH equation as the voids concentration

include/pf-applications/time_integration/time_integrators.h
This to make this function work with the data stored per quadrature point during linearization.
=> Overload `compute_time_derivative()`

applications/sintering/include/pf-applications/sintering/postprocessors.h
Otherwise an exception is triggered in debug mode inside `dealii::Triangulation::get_manifold()`.
=> Set manifold_id to a flat one after not needed

applications/sintering/scripts/paraview_grain_contours_tex.py
1. Add handling of multiple segments per grain.
2. Output segment type (spherical).
3. Parse 2D VTK files ignoring cross-sections.
=> Improve Paraview VTK contours

applications/sintering/include/pf-applications/sintering/driver.h, applications/sintering/include/pf-applications/sintering/parameters.h
Currently if `GrainTracker::ExcGrainsInconsistency` is thrown somewhere during grain tracking, then the solver crashes. However, this is a recoverable scenario. Such an error simply means that we have made a too large timestep and we can attempt to perform a smaller one. Handling this required to modify a bit the logic of the time loop in the driver.
=> Attempt to recover grains inconsistency detect during grain tracking

applications/sintering/include/pf-applications/sintering/driver.h, include/pf-applications/time_integration/time_marching.h
This refactoring simplifies the driver and prepares it for the subsequent introduction of explicit time integration strategies. Most of the nonlinear related things have been wrapped inside a `TimeMarchingImplicit` class.
=> Introduce time marching

applications/sintering/include/pf-applications/sintering/operator_sintering_generic.h, applications/sintering/include/pf-applications/sintering/preconditioners.h, tests/residual_generic_scalar_no_rbm.mpirun=1.output, tests/residual_generic_scalar_no_rbm.mpirun=2.output, tests/residual_generic_scalar_no_rbm.mpirun=3.output, tests/residual_generic_scalar_rbm.mpirun=1.output, tests/residual_generic_scalar_rbm.mpirun=2.output, tests/residual_generic_scalar_rbm.mpirun=3.output, tests/residual_generic_tensorial_no_rbm.mpirun=1.output, tests/residual_generic_tensorial_no_rbm.mpirun=2.output, tests/residual_generic_tensorial_no_rbm.mpirun=3.output, tests/residual_generic_tensorial_rbm.mpirun=1.output, tests/residual_generic_tensorial_rbm.mpirun=2.output, tests/residual_generic_tensorial_rbm.mpirun=3.output
Previously the equation for chemical potential was written such that the primary variable itself had a negative sign. This is not very convenient for generalization of various time stepping strategies to be implemented (implicit and explicit). I inverted the sign. Now the primary unknowns of both time-dependent and algebraic equations enter with positive signs.
=> Invert sign of the chemical potential equation

applications/sintering/include/pf-applications/sintering/driver.h, applications/sintering/include/pf-applications/sintering/operator_sintering_data.h, applications/sintering/sintering_throughput.cc, benchmarks/layer_wise.likwid.cc, include/pf-applications/time_integration/time_integrators.h, tests/advection_mechanism_data.cc, tests/include/pf-applications/tests/sintering_model.h, tests/microstructure_from_imaging.cc
The `dts` vector in driver was very confusing. I encapsulated it inside `TimeIntegratorData`, which is also now responsible for its serialization. I modified the tests and other executable accordingly.
=> Encapsulate dts
