include/pf-applications/base/debug.h
include/pf-applications/grain_tracker/tracker.h

references https://github.com/hpsint/hpsint/issues/497

Revert remapping optimizations (#478, #482)

---

include/pf-applications/lac/preconditioners.h

... via multi vectors (similar to https://github.com/kronbichler/adaflo/blob/926aa96b76f5a9af63890c891808d9e7310455f2/include/adaflo/block_matrix_extension.h#L61-L92)

Batched ILU

---

applications/sintering/include/pf-applications/sintering/driver.h
include/pf-applications/grain_tracker/tracker.h

As proposed here https://github.com/hpsint/hpsint/issues/497#issuecomment-1460148335

Detect all invalid grains and only then throw an exception

---

applications/sintering/include/pf-applications/sintering/driver.h
applications/sintering/include/pf-applications/sintering/parameters.h
include/pf-applications/base/debug.h
include/pf-applications/grain_tracker/tracker.h

It is possible to switch now between the new and the old algorithms, the new one is used by default. Once the new algo is settled proves its robustness, the old is to be removed.

New remapping algo

---

include/pf-applications/grain_tracker/distributed_stitching.h

First try, check other options too.

Better detection of particles

---

include/pf-applications/lac/dynamic_block_vector.h

Simplify and fix DynamicBlockVector

---

applications/sintering/include/pf-applications/sintering/driver.h
include/pf-applications/lac/dynamic_block_vector.h
include/pf-applications/matrix_free/tools.h

extracted from https://github.com/hpsint/hpsint/pull/378

Remove MatrixFree::cell_loop() work around

---

applications/sintering/include/pf-applications/sintering/creator.h
tests/include/residual_tester.h
tests/include/sintering_model.h
tests/include/tangent_tester.h
tests/residual_generic_scalar_no_rbm.cc
tests/residual_generic_scalar_no_rbm.mpirun=1.output
tests/residual_generic_scalar_no_rbm.mpirun=2.output
tests/residual_generic_scalar_no_rbm.mpirun=3.output
tests/residual_generic_scalar_rbm.cc
tests/residual_generic_scalar_rbm.mpirun=1.output
tests/residual_generic_scalar_rbm.mpirun=2.output
tests/residual_generic_scalar_rbm.mpirun=3.output
tests/residual_generic_tensorial_no_rbm.cc
tests/residual_generic_tensorial_no_rbm.mpirun=1.output
tests/residual_generic_tensorial_no_rbm.mpirun=2.output
tests/residual_generic_tensorial_no_rbm.mpirun=3.output
tests/residual_generic_tensorial_rbm.cc
tests/residual_generic_tensorial_rbm.mpirun=1.output
tests/residual_generic_tensorial_rbm.mpirun=2.output
tests/residual_generic_tensorial_rbm.mpirun=3.output
tests/tangent_generic_scalar.mpirun=2.output
tests/tangent_generic_scalar.mpirun=3.output
tests/tangent_generic_tensorial.mpirun=2.output
tests/tangent_generic_tensorial.mpirun=3.output

Enhance tests for sintering operators:
- Different ranks
- Tests for residuals (not only for tangents)

Sintering operators residual tests

---

applications/sintering/include/pf-applications/sintering/driver.h
applications/sintering/include/pf-applications/sintering/parameters.h
applications/sintering/include/pf-applications/sintering/postprocessors.h

This feature is used in the 5 particles MOOSE comparison experiments in the paper.

Order parameters domain intergrals

---

applications/sintering/include/pf-applications/sintering/postprocessors.h
include/pf-applications/grain_tracker/distributed_stitching.h
include/pf-applications/grain_tracker/tracker.h

I am working on more advanced analysis of porosity. This is a minor preliminary modification for that purpose.

Grain tracker - extract local connectivity function

---

include/pf-applications/grain_tracker/distributed_stitching.h
include/pf-applications/grain_tracker/tracker.h

The follow up of #535. Another function has been extracted, will be helpfull for porosity analysis too.

Grain tracker calc particles info

---

applications/sintering/include/pf-applications/sintering/driver.h
applications/sintering/include/pf-applications/sintering/parameters.h
applications/sintering/include/pf-applications/sintering/postprocessors.h
include/pf-applications/grain_tracker/grain.h
include/pf-applications/grain_tracker/segment.h
include/pf-applications/grain_tracker/tracker.h

To obtain not only pore sizes distribution but also grain sizes distribution.

Output grain stats

---

applications/sintering/include/pf-applications/sintering/driver.h
applications/sintering/include/pf-applications/sintering/parameters.h
applications/sintering/include/pf-applications/sintering/postprocessors.h
include/pf-applications/grain_tracker/distributed_stitching.h

Basically, this prints a list of all pores to a file.

Output porosity stats

---

applications/sintering/include/pf-applications/sintering/driver.h
applications/sintering/include/pf-applications/sintering/postprocessors.h

Various minor improvements:
1. Add `const`
2. Write table via buffer
3. Provide only concentration for writing the corresponding contour
4. Use new graph based stitching algo

Postproc improvements

---

applications/sintering/include/pf-applications/sintering/postprocessors.h
applications/sintering/sintering.cc

Fixes #521 for SuperMUC for large problems but still keeps `MyDataOut` as an option.

Make MyDataOut optional

---

include/pf-applications/lac/solvers_linear.h

After the recent deal.II changes.

Change NS for OrthogonalizationStrategy

---

applications/sintering/batch_runs/batch_example_via_cmd.json
applications/sintering/batch_runs/run_batch.py

I will merge it since it is very minor

Move slurm options to the other section

---

include/pf-applications/base/geometry.h
include/pf-applications/grain_tracker/tracker.h
include/pf-applications/grain_tracker/tracking.h
tests/transfer_grain_ids_01.cc
tests/transfer_grain_ids_01.output
tests/transfer_grain_ids_02.cc
tests/transfer_grain_ids_02.output
tests/transfer_grain_ids_03.cc
tests/transfer_grain_ids_03.output
tests/transfer_grain_ids_04.cc
tests/transfer_grain_ids_04.output
tests/transfer_grain_ids_05.cc
tests/transfer_grain_ids_05.output
tests/transfer_grain_ids_06.cc
tests/transfer_grain_ids_06.output

The code can be reviewed already.
Should be merged prior to #564.

Track grains with rtrees

---

applications/sintering/include/pf-applications/sintering/operator_advection.h

The old verson deadlocks in the MPI case if only on some ranks the problems were detected.

Refactor loop in the Courant check 

---

applications/sintering/scripts/distribution_analysis.py
applications/sintering/scripts/library.py
applications/sintering/scripts/plot_data.py
applications/sintering/scripts/postproc_shrinkage.py
applications/sintering/scripts/track_grain_data.py

Improve existing and add also 1 new script to make plots of evolution of grain centers and forces ver time.

Improve postproc scripts

---

applications/sintering/include/pf-applications/sintering/driver.h
applications/sintering/include/pf-applications/sintering/parameters.h
applications/sintering/include/pf-applications/sintering/postprocessors.h

Output these 3 quantities separately, previously only the bulk part was available in the output.

Add bulk, interface and total energies

---

applications/sintering/include/pf-applications/sintering/driver.h

Otherwise crashes after restart if the Courant check is enable.

Precompute cells after restart

---

applications/sintering/include/pf-applications/sintering/operator_advection.h

This minor issue was first noted in #459.

Fix index in OperatorAdvection

---

applications/sintering/scripts/distribution_analysis.py
applications/sintering/scripts/library.py
applications/sintering/scripts/packing_properties.py
applications/sintering/scripts/plot_data.py
applications/sintering/scripts/plot_distribution_history.py
applications/sintering/scripts/postproc_shrinkage.py
applications/sintering/scripts/track_grain_data.py

Minor improvements to the postprocessing scripts to make them more robust and report better errors.

Postproc scripts improvement

---

applications/sintering/scripts/library.py
applications/sintering/scripts/plot_data.py
applications/sintering/scripts/postproc_shrinkage.py

Minor improvements: custom labels, delimeters and also skip zero first entries in the list as the reference values when computing shrinkage.

Minor improvements of some postproc scripts

---

applications/sintering/include/pf-applications/sintering/operator_base.h
applications/sintering/include/pf-applications/sintering/operator_sintering_generic.h
include/pf-applications/lac/dynamic_block_vector.h
include/pf-applications/lac/solvers_nonlinear.h
include/pf-applications/matrix_free/tools.h

Jacobi-Free implementation with pre/post

---

applications/sintering/include/pf-applications/sintering/advection.h
applications/sintering/include/pf-applications/sintering/driver.h
applications/sintering/include/pf-applications/sintering/operator_advection.h
applications/sintering/include/pf-applications/sintering/operator_base.h
applications/sintering/include/pf-applications/sintering/residual_wrapper.h
tests/include/residual_tester.h
tests/include/sintering_model.h
tests/include/tangent_tester.h

A new version of #590. The initial PR became inapropriate after #378 has been merged due to pre/post.

Improve `JacobianFree` wrapper - new version

---

applications/sintering/scripts/plot_data.py

Some minor improvements of the plotting script.

Plot data improvement

---

applications/sintering/scripts/make_animated_plot.py

This is to have some nice videos like this.
https://github.com/hpsint/hpsint/assets/8836201/b550aae7-0fb1-4cee-aa88-64749b578b3f

A script that creates animated plots

---

applications/sintering/include/pf-applications/sintering/driver.h
applications/sintering/include/pf-applications/sintering/postprocessors.h
include/pf-applications/grid/bounding_box_filter.h

A smarter bounding box algorithm that allows the MCA to create smoother croping.
old algo | new algo
:-------------------------:|:-------------------------:

Smooth bounding box filter

---

applications/sintering/scripts/distribution_analysis.py
applications/sintering/scripts/library.py
applications/sintering/scripts/make_animated_distribution.py
applications/sintering/scripts/make_animated_plot.py

With this, #595, #597 and #598 one can create animations like this.
https://github.com/hpsint/hpsint/assets/8836201/70f2d77d-dbf1-40df-a106-64232f02bcc3

Script to create animated size distribution and also some minor improvements

---

applications/sintering/include/pf-applications/sintering/postprocessors.h
applications/sintering/scripts/plot_data.py

Some minor improvements in different parts of the code mainly related to the results postprocessing.

Minor improvements for postprocessing

---

applications/sintering/include/pf-applications/sintering/driver.h

With https://github.com/dealii/dealii/pull/16329 everything should work fine now.

Disable NOX Newton rescue

---

applications/sintering/scripts/library.py
applications/sintering/scripts/plot_data.py
applications/sintering/scripts/postproc_shrinkage.py
applications/sintering/scripts/track_grain_data.py

A minot thing to have better control over the labels length.

Postrpocessing: extend labels

---

applications/sintering/batch_runs/jobs_submitter.py

By default we are interested in jobs running on `test` only, makes sense.

Count jobs on a given partition in jobs_submitter

---

applications/sintering/include/pf-applications/sintering/postprocessors.h

Fix bug with null ptr dereference

---

applications/sintering/include/pf-applications/sintering/driver.h
applications/sintering/include/pf-applications/sintering/parameters.h
include/pf-applications/matrix_free/output.h

I use this sometimes for debugging.

Output matrix free indices to VTK

---

applications/sintering/include/pf-applications/sintering/operator_sintering_base.h
applications/sintering/include/pf-applications/sintering/operator_sintering_coupled_base.h
applications/sintering/include/pf-applications/sintering/operator_sintering_generic.h

Output velocities for coupled operators

---

include/pf-applications/lac/dynamic_block_vector.h
inst.cc

#630 fails to compile since, it seems, some changes were made to deal.II

Fix DBV interface in order to compile with recent deal.II

---

applications/sintering/include/pf-applications/sintering/driver.h
applications/sintering/include/pf-applications/sintering/postprocessors.h

This is computed from the displacement field simply by taking its value at the center of each particle using `RemotePointEvaluation`.

Grain velocity for coupled models

---

applications/sintering/batch_runs/run_batch.py
applications/sintering/scripts/transform_packing.py

Some minor improvements to a coupled of scripts

Add force clear option, change priority for batcher and fix label for transform scripts

---

applications/sintering/scripts/distribution_analysis.py
applications/sintering/scripts/packing_properties.py
applications/sintering/scripts/paraview_shrinkage.py
applications/sintering/scripts/postproc_shrinkage.py

This is to make it possible to postprocess multiple files with no need to close matplotlib popups.

Add skip plot option

---

applications/sintering/scripts/extract_subpacking.py
applications/sintering/scripts/packing_properties.py
applications/sintering/scripts/paraview_2particles.py
applications/sintering/scripts/postproc_shrinkage.py
applications/sintering/scripts/track_grain_data.py

Useful for generating complex postprocessing results

Add suffixes to file names in scripts to customize output files

---

applications/sintering/include/pf-applications/sintering/postprocessors.h

To comply with parsing from #642.

Improve tex contours output

---

applications/sintering/include/pf-applications/sintering/boundary_conditions.h
applications/sintering/include/pf-applications/sintering/driver.h
applications/sintering/include/pf-applications/sintering/parameters.h
include/pf-applications/grain_tracker/tracking.h

Used for imposition of boundary conditions.

Compute particle cloud barycenter

---

applications/sintering/include/pf-applications/sintering/postprocessors.h
applications/sintering/scripts/build_tex_packings.py

The code is basically inherited from deal.II parallel VTU output.

Write tex contours in parallel with MPI 

---

applications/sintering/include/pf-applications/sintering/parameters.h

@peterrum, I will merge it right away, this is a super minor bug fix.

Move strains output option to the right place

---

applications/sintering/include/pf-applications/sintering/operator_sintering_generic.h

An improvement of #648 to make it work with both old and new versions of deal.II.

Add type definitions

---

applications/sintering/include/pf-applications/sintering/driver.h
applications/sintering/include/pf-applications/sintering/postprocessors.h
applications/sintering/include/pf-applications/sintering/projection.h
include/pf-applications/numerics/output.h

The continuation of #651: one can now output projected grain contours.
I am planning to refactor the code a bit to reduce its redundancy in a follow up PR.

Projected grain contours

---

applications/sintering/include/pf-applications/sintering/postprocessors.h
applications/sintering/include/pf-applications/sintering/projection.h
include/pf-applications/grain_tracker/mapper.h
include/pf-applications/grain_tracker/tracker.h

Refactor grain contours vtu

---

applications/sintering/scripts/build_tex_packings.py
applications/sintering/scripts/paraview_grain_contours_tex.py

This script produces the same output as in #651, but does it via Paraview and uses the already created 3D VTK contour plots. This is quite handy for situations when a certain section can not be predefined beforehand.

Create TEX contours from 3D VTK contours

---

applications/sintering/include/pf-applications/sintering/postprocessors.h

Add missing update/zero_out calls for ghosts in some postprocessor functions

---

applications/sintering/include/pf-applications/sintering/driver.h
applications/sintering/include/pf-applications/sintering/parameters.h
applications/sintering/include/pf-applications/sintering/postprocessors.h

This is a handy metric to assess densification.
Later I will also the per grain output to the grain contour plots.

Compute average coordination number

---

applications/sintering/include/pf-applications/sintering/boundary_conditions.h
applications/sintering/include/pf-applications/sintering/driver.h
applications/sintering/include/pf-applications/sintering/operator_sintering_coupled_base.h
applications/sintering/include/pf-applications/sintering/parameters.h
applications/sintering/include/pf-applications/sintering/preconditioners.h
include/pf-applications/base/debug.h

Most of the changes related to the general infrastructure of the solver can already be integrated into the main repo. I need to test them a bit prior, so WIP for a while.

Take features from experimental

---

include/pf-applications/base/debug.h
include/pf-applications/base/output.h
include/pf-applications/grain_tracker/grain.h
include/pf-applications/grain_tracker/output.h
include/pf-applications/grain_tracker/representation.h
include/pf-applications/grain_tracker/segment.h
include/pf-applications/grain_tracker/tracker.h
inst.cc
tests/grains_serialization.cc

This PR prepares the grain tracker infrastructure to use spherical or elliptical representations of grains in the next PRs.

Introduce segment representations

---

include/pf-applications/lac/preconditioners.h

Fix code due to deal.II PR [17847](https://github.com/dealii/dealii/pull/17847) and for this reason #697 failed to compile.

Fix ComputeIndexOwner compilation error due to deal.II PR 17847

---

applications/sintering/include/pf-applications/sintering/driver.h
applications/sintering/include/pf-applications/sintering/operator_sintering_generic.h
applications/sintering/include/pf-applications/sintering/preconditioners.h

Refactoring of the callbacks inside operators within the `BlockPreconditioner2`.

Add stateful nonlinear operator to `BlockPreconditioner2`

---

applications/sintering/include/pf-applications/sintering/driver.h
applications/sintering/include/pf-applications/sintering/operator_sintering_base.h
applications/sintering/include/pf-applications/sintering/operator_sintering_data.h
applications/sintering/include/pf-applications/sintering/operator_sintering_generic.h
applications/sintering/include/pf-applications/sintering/preconditioners.h
applications/sintering/include/pf-applications/sintering/runner.h
applications/sintering/sintering_generic.cc
applications/sintering/sintering_throughput.cc
benchmarks/layer_wise.likwid.cc
include/pf-applications/numerics/power_helper.h
tests/advection_mechanism_data.cc
tests/include/pf-applications/tests/sintering_model.h

This PR allows one to customize free energy of the operator.

Custom free energy

---

applications/sintering/grain_tracker_throughput.cc
applications/sintering/include/pf-applications/sintering/initial_values.h
applications/sintering/include/pf-applications/sintering/initial_values_array.h
applications/sintering/include/pf-applications/sintering/initial_values_ch_ac.h
applications/sintering/include/pf-applications/sintering/initial_values_circle.h
applications/sintering/include/pf-applications/sintering/initial_values_cloud.h
applications/sintering/include/pf-applications/sintering/initial_values_debug.h
applications/sintering/include/pf-applications/sintering/initial_values_hypercube.h
applications/sintering/include/pf-applications/sintering/initial_values_microstructure.h
applications/sintering/include/pf-applications/sintering/initial_values_microstructure_imaging.h
applications/sintering/include/pf-applications/sintering/initial_values_microstructure_voronoi.h
applications/sintering/include/pf-applications/sintering/initial_values_spherical.h
applications/sintering/include/pf-applications/sintering/runner.h

This PR make the initial values classes able to work either CH or AC or CH+AC systems.

Refactor initial values

---

applications/sintering/include/pf-applications/sintering/initial_values.h
applications/sintering/include/pf-applications/sintering/parameters.h
applications/sintering/include/pf-applications/sintering/runner.h

And also slight refactoring of the runner.

Add 2 other initial conditions to the runner

---

applications/sintering/include/pf-applications/sintering/driver.h

It is more convenient for some advanced PF models.

Split CH norm into two

---

applications/sintering/include/pf-applications/sintering/driver.h
applications/sintering/include/pf-applications/sintering/parameters.h
include/pf-applications/lac/solvers_linear.h

For debug and prototyping purposes, this option can de useful, especially if FDM approximations are used all over the place.

Add direct linear solver

---

include/pf-applications/lac/solvers_linear.h

Otherwise the coupled code from another repo fails to compile.

Add missing include

---

applications/sintering/include/pf-applications/sintering/preconditioners.h

There was a bug leading to the systems not being updated.

Force to update BlockPreconditioner2 systems

---

applications/sintering/include/pf-applications/sintering/driver.h

The automatic box may turn out to be having negative dimension along one of the coordinates - we do not want this.

Check if control boxes are admissible

---

applications/sintering/include/pf-applications/sintering/driver.h
applications/sintering/include/pf-applications/sintering/postprocessors.h
applications/sintering/include/pf-applications/sintering/projection.h

There were a few bugs in the code arising in specific situations of the multirank runs. The bug from #724 was one of them.

Improve output of sections in MPI environments

---

applications/sintering/scripts/paraview_draw_packings.py

A script to draw packings using pvpython.

Paraview draw packings

---

applications/sintering/include/pf-applications/sintering/driver.h
applications/sintering/include/pf-applications/sintering/initial_values_array.h
applications/sintering/include/pf-applications/sintering/initial_values_circle.h
applications/sintering/include/pf-applications/sintering/initial_values_cloud.h
applications/sintering/include/pf-applications/sintering/initial_values_hypercube.h
applications/sintering/include/pf-applications/sintering/operator_sintering_generic.h
applications/sintering/include/pf-applications/sintering/particle.h
benchmarks/operators.h
include/pf-applications/grid/constraint_helper.h
tests/include/pf-applications/tests/sintering_model.h
tests/tensor_product_kernels_01.cc

Most of the dimension checks have been made constexpr. Some minor algos generalizations have been performed.

Improve dim handling

---

applications/sintering/include/pf-applications/sintering/parameters.h
applications/sintering/include/pf-applications/sintering/preconditioners.h
include/pf-applications/lac/preconditioners.h
include/pf-applications/lac/solvers_linear.h
include/pf-applications/lac/solvers_linear_parameters.h
include/pf-applications/lac/solvers_nonlinear_parameters.h

Function `create()` similar to the one used for creating preconditioners has been added for linear solvers.
Plus some minor `const`-related refactoring.

Linear solvers factory

---

include/pf-applications/lac/dynamic_block_vector.h

This is required for #741 to compile

Add DBV move ctor

---

applications/sintering/include/pf-applications/sintering/operator_grain_growth.h
applications/sintering/include/pf-applications/sintering/operator_grand_potential_greenquist.h
applications/sintering/include/pf-applications/sintering/operator_sintering_base.h
include/pf-applications/base/fe_integrator.h
include/pf-applications/time_integration/time_integrators.h

Mainly I got rid of BDFIntegrator, it was obsolete. This simplified the code.

Refactor velocity evaluation

---

applications/sintering/grain_tracker_throughput.cc
applications/sintering/include/pf-applications/sintering/advection.h
applications/sintering/include/pf-applications/sintering/operator_sintering_data.h
applications/sintering/include/pf-applications/sintering/postprocessors.h
applications/sintering/include/pf-applications/sintering/projection.h
applications/sintering/src/tools.cc
include/pf-applications/base/output.h
include/pf-applications/dofs/dof_tools.h
include/pf-applications/grid/grid_tools.h
src/base/output.cc
src/grid/grid_tools.cc
tests/adjust_divisions.cc
tests/advection_mechanism_data.cc
tests/distributed_distances.cc
tests/grain_tracker_advection_periodic.cc
tests/grain_tracker_elliptical.cc
tests/grain_tracker_periodic_corner.cc
tests/include/pf-applications/tests/mesh_tester.h
tests/include/pf-applications/tests/microstructure_tester.h
tests/include/pf-applications/tests/sintering_model.h
tests/initial_mesh_102p_from_interface.cc
tests/initial_mesh_102p_from_max_radius.cc
tests/initial_mesh_212p_from_interface.cc
tests/initial_mesh_212p_from_max_radius.cc
tests/initial_mesh_51p_from_interface.cc
tests/initial_mesh_51p_from_max_radius.cc

I moved some grid related functions out of sintering applications to the library level - they are quite general and can be used for other applications too.

Refator grid functions
